### ISSUE TITLE
File PDF check not working

### ISSUE THREAD

**Issue by icangku** [websanova/vue-upload#15]
` this.$upload.new('file', {`
`        startOnSelect: false,`
`        extensions: ['application/pdf'] // or ['pdf'],`
`        onSelect(files) {`
`          this.handleFileUpload('', '', '', files, "")`
`        },`
`        onError(err) {`
`          this.$message.error('Error uploading file.');`
 `       }`
`    });`

Vue JS 2.x
Thank you

**Comment by websanova** [comment]
Well it's checking for extension not mime type, so it should be "pdf".

But no idea what you're really asking me here, it's server side or client side, extension check, upload failing... ???

**Comment by icangku** [comment]
its client side, i had tried 'pdf' also but its not working

**Comment by websanova** [comment]
Can you be more specific, are you sure the file is correct, did you try
other files and extensions, etc...

**Comment by icangku** [comment]
I did try, how can i be more specific? i tried upload pdf files but not working, it gives error, 
i tried 
`extensions: ['application/pdf']` and 
`extensions: ['pdf']`
 both not working

**Comment by websanova** [comment]
I mean.. did you try a jpg or png extension, file and config...?

**Comment by icangku** [comment]
for jpg and png file its working, that's why i asked why pdf file not working?

**Comment by websanova** [comment]
So double check your stuff.

It's just looking for an file extension, nothing to do with pdf.

**Comment by icangku** [comment]
but why its not working, i've tried several pdf files, and still not working,  btw how do i see the error ?

**Comment by icangku** [comment]
man, its really not working, it only works with image file, other types cannot be uploaded, help me please!!

at least help me, how to find out what's behind Error Uploading, because there's no error log showing

**Comment by websanova** [comment]
Dude, if you want help you have to provide some way for other people to reproduce the problem, don't just cry for help.

I just tested the extensions and it works fine for me, no idea what you're doing or where your error is coming from.
