### ISSUE TITLE
body not working ? part 2

### ISSUE THREAD

**Issue by icangku** [websanova/vue-upload#16]
how to access this in body options ?  
`body : { reviewId : this.review},`
it doesn't work
i got undefined

**Comment by websanova** [comment]
What do you mean?

**Comment by icangku** [comment]
when i'm trying to see what's the value of reviewId in my server it gave 'undefined'
I'm using Laravel like this :
dd($request->reviewId);
or when i'm using 

` this.$upload.reset('ttdp', {`
`     url: `reviews/ttd/upload/${this.review.id}``
`});`

still doesn't work it gave undefined also

**Comment by websanova** [comment]
Do you see it in request?

**Comment by icangku** [comment]
yes

**Comment by icangku** [comment]
`  created(){`
 `   this.$upload.new('ttdr', {`
 `     extensions: ['jpeg', 'jpg', 'png'],`
 `     onSelect(file) {`
 `       file[0].preview((file) => {`
 `         this.ttd_reviewer = file.raw`
 `       })`
 `     },`
 `     onError() {`
 `       this.$message.error('Error uploading file.');`
 `     }`
 `   });`
 ` },`
 ` mounted(){`
 `   this.$upload.reset('ttdp', {`
 `     url: 'reviews/' + this.$auth.user().id + '/ttd'`
 `   });`
 ` },`

 Route::post('reviews/{id}/ttd', 'ReviewController@uploadTTD');
dd($request->id);

Its not working, it seems there's no something wrong

**Comment by websanova** [comment]
Well if you see it in the request then your issue is in Laravel not the
plug-in ;)

**Comment by icangku** [comment]
![a](https://user-images.githubusercontent.com/14269158/39854599-93408070-5452-11e8-81b7-28607810058e.png)

That's the result

**Comment by icangku** [comment]
` function _http(data) {`
`        console.log(data.url)`
`        this.Vue.http.post(data.url, data.body, {progress: data.progress}).then(data.success, data.error);`
`    }`

it returns undefined,  so its not Laravel issue

**Comment by icangku** [comment]
so how ? please help me

**Comment by websanova** [comment]
I don't really know what you're asking man.
