### ISSUE TITLE
Increment progress rather than direct 0 to 100?

### ISSUE THREAD

**Issue by Robthegod23** [websanova/vue-upload#18]
Is there anyway to increment the `percentComplete` rather than going directly from 0 to 100?

**Comment by websanova** [comment]
It's using the browsers provided progress on the upload. I assume you are testing locally with small files so you are seeing this jump.

**Comment by Robthegod23** [comment]
yes I am developing locally with files about 4-7MB in size... so native behavior for the progress is a gradual increment rather than jump?
