### ISSUE TITLE
parseErrors behaviour

### ISSUE THREAD

**Issue by franksl** [websanova/vue-upload#21]
Hello,
I noticed that in the new version the behaviour of parseError option has changed.
I have an onError handler that does this:

```
onError: function (f, res) {
    if (f) {
        console.log(f.name)
        console.log(f.errors[0].msg);
    }
}
```

The previous implementation of my custom parseError was like this (as still documented):
```
parseErrors: function (error) {
    return [{
        rule: 'fileError',
        msg: 'Error!'
    }];
}
```

This makes the onError wrong because onError receives f.errors as an array of arrays. To be able to keep onError unchanged I had to modify parseErrors like this (removing []):

```
parseErrors: function (error) {
    return {
        rule: 'fileError',
        msg: 'Error!'
    };
}
```

Can you please clarify what is the correct behaviour?
Thanks,
Frank

**Comment by websanova** [comment]
Added some change log and fixed up docs for this.

Note it's released under v1.0.0-beta now.
