### ISSUE TITLE
Error: Vue is not defined (v1.0.0-beta)

### ISSUE THREAD

**Issue by dzafel** [websanova/vue-upload#23]
Just updated the module to 1.0.0-beta in my app and I got this error:
`ReferenceError: Vue is not defined` in [this file/line](https://github.com/websanova/vue-upload/blob/17b56f2b03c7ef47a9724085b9934a8c2724c5dd/src/upload.js#L64)
I'm assuming it should be `__upload.Vue.set`

btw. I see a few changes that were not reflected in your docs, for example:

- all events have an additional parameter now (file), passed as the first argument to the callback function so instead `onSuccess(res)` it's now `onSuccess(file, res)`
- errors are objects `{code: , msg: }` but in examples the `.message` is used instead of `.msg`
I needed to look at the code to find out why my code didn't work after update to 1.0.0

Anyway, thanks for the great module!

**Comment by websanova** [comment]
Yes, whoops, that's fixed. Just grab the latest `v1.0.1-beta`.

I've also just added a build script and support for `import` syntax.

So you will need to add the plugin like:

~~~
import vueUpload from '@websanova/vue-upload';

Vue.use(vueUpload);
~~~

OR

~~~
Vue.use(require('@websanova/vue-upload').default);
~~~
