### ISSUE TITLE
Not working with axios

### ISSUE THREAD

**Issue by jigarzon** [websanova/vue-upload#29]
Hi, I tried to understand docs, its not enough clear for me how to include axios. It explains the `http` function but not how to include it in the `$upload` object. I use:

```
  this.$upload.option('msg-files', {
        url: url,
        extensions: ['jpeg', 'jpg', 'png'],
        'http': (data) => {
          console.log("starting to get axios");
          axios.post(data.url, data.body, {
            onUploadProgress: data.progress
          }).then(data.success, data.error)
        }
      });
```
 But doesn;t work, it says ` Uncaught TypeError: Cannot read property 'post' of undefined`

**Comment by websanova** [comment]
Yea, so it doesn't know what axios is, so something with your setup. Can you console  `this` or `Vue` and see what you get...

**Comment by jigarzon** [comment]
Yes I figured it out, thanks for your response. Its still a bug I think, as the docs are not clear enough.
You cannot use:
`  this.$upload.option('msg-files', {'url':'https://example.com/', 'extensions': ['jpg']});` for example, because one of the parameters will not effectively be set, just one of them (I think its the last one).
So I had to do the configuration in this way:
```
  this.$upload.option('msg-files', 'parseErrors', function(error) {
        console.error("Error while uploading", error);
        return [{
          code: 'fileError',
          msg: error
        }];

      });
      this.$upload.option('msg-files', 'url', url);
      this.$upload.option('msg-files', 'extensions', ['jpeg', 'jpg', 'png']);
      this.$upload.option('msg-files', 'http', function(data) {
        console.log("starting to get axios");
        axios.post(data.url, data.body, {
          onUploadProgress: data.progress,
          headers: {
            'x-auth-token': credentials.token
          }
        }).then(data.success, data.error)
      });
    });
```
And now its working

**Comment by jigarzon** [comment]
The issue has nothing to do with axios, Axios was generating an error because the "http" config value was never set as expected. Maybe this issue can be closed and I can generate a new one, but its an enhancement (configure multiple values in one call)

**Comment by websanova** [comment]
That's intended, `option` is for setting one option.

Otherwise you should set things like `http` in the install config so that it can be reused for each upload instance.

~~~
Vue.use(vueUpload, {
    http: function () { /* axios */ }
});
~~~

 or using `new` method if it's specific for that instance...

**Comment by Sell24** [comment]
Just a suggestion that perhaps including that "option is only intended for setting one option" in the read.me file would be helpful. I also fell into the same trap and couldn't understand why nothing seemed to be working.

**Comment by websanova** [comment]
Not sure what you mean. Feel free to submit a pull request if you feel the docs can be improved.

**Comment by Sell24** [comment]
I just meant I tried to set all my options in one statement like @jigarzon rather than individually as required.  

I just happened to see this because I could not figure out why my Axios function was not being called. If I wasnt using Axios, I am not sure I would have stumbled upon this and would still be trying to get this to work. (Please dont take that last statement as an offense, as it was not at all intended that way. I realize this is all part of the learning process of understanding how to use this component on my end and I am reading the docs to understand).
