### ISSUE TITLE
option body maybe not working ? 

### ISSUE THREAD

**Issue by marvinosswald** [websanova/vue-upload#3]
I'm trying to append something like 
```
this.$upload.new('logo-image', {
body:{
     key: 'logo-image'
},
....
```
but it doesn't appear in the payload or headers..

what am i doing wrong ?

**Comment by websanova** [comment]
Hmm, are you using axios?

**Comment by marvinosswald** [comment]
no i don't should i ?

**Comment by websanova** [comment]
Shouldn't matter, it's fairly new plugin. Maybe something not working. Need
to check.

**Comment by marvinosswald** [comment]
As i'm trying to investigate the problem i came along this line: 
[`fileUploadFormData.append(uploader.options.name, file.$file);`](https://github.com/websanova/vue-upload/blob/master/src/upload.js#L272)

Maybe i'm missing it but i think here should the option body be added ?

Cheers

**Comment by websanova** [comment]
Yes, I think it needs to loop through the body field and add each one as a
separate FormData.append line.

**Comment by websanova** [comment]
Thx again.

**Comment by websanova** [comment]
Latest is up on npm v0.2.7-beta.

**Comment by icangku** [comment]
how to access this in body options ?  
`body : { reviewId : this.review},`
it doesn't work
i got undefined

**Comment by Robthegod23** [comment]
using axios, exactly what is the name of the payload I'm expected to recieve to my backend? I'm using Laravel and I'm attempting `$request->file('file')` but nothing... what is it being sent as?

**Comment by websanova** [comment]
Why don't you open your dev tools and confirm...

This is example with form data as well ;)

```
------WebKitFormBoundarypcpgiosMoKygBWm7
Content-Disposition: form-data; name="file"; filename="a2002011001-e02-128k.ogg"
Content-Type: audio/ogg


------WebKitFormBoundarypcpgiosMoKygBWm7
Content-Disposition: form-data; name="project_id"
```
