### ISSUE TITLE
file.clear() does not work on files with 'error' state

### ISSUE THREAD

**Issue by janiskelemen** [websanova/vue-upload#32]
Hi,

the file.clear() function works fine on files with the state 'success' but it returns an error if the uploaded file has a state of 'error':

`Uncaught TypeError: Cannot read property 'file' of undefined`

**Comment by websanova** [comment]
Can you provide a better example of what you're doing.

**Comment by shinsenter** [comment]
@websanova 
Same issue with #33

**Comment by websanova** [comment]
ok, that's fixed now just pull the latest :-)
