### ISSUE TITLE
Calling splice inside a for loop

### ISSUE THREAD

**Issue by shinsenter** [websanova/vue-upload#33]
When removing items from array with splice in for loop, the indexes of the array change.
It causes unexpected errors when I'm try resetting the upload instance after adding few invalid files.

https://github.com/websanova/vue-upload/blob/418450074c814ca5046c8db76c723ef507e4b66c/src/upload.js#L335

**Comment by shinsenter** [comment]
#32

**Comment by websanova** [comment]
You can try error.clear() on the error you want to remove.

**Comment by shinsenter** [comment]
Errors also occur when calling .reset(name)

**Comment by shinsenter** [comment]
@websanova 
You can also fix this by adding a `break` after this
https://github.com/websanova/vue-upload/blob/418450074c814ca5046c8db76c723ef507e4b66c/src/upload.js#L335

**Comment by websanova** [comment]
ok, you can try 1.1.7-beta

**Comment by shinsenter** [comment]
@websanova 
https://github.com/websanova/vue-upload/commit/4c3db3401b773896637c86e6425b6e6605a1d7b9
LGTM. Thank you.
