### ISSUE TITLE
'remove' method does not exist

### ISSUE THREAD

**Issue by Sell24** [websanova/vue-upload#37]
The document specifies a 'remove' function which appears to no longer exist.  Is it possible to add this back   or is there an alternate way of achieving the same thing?

**Comment by websanova** [comment]
Tru clear

**Comment by Sell24** [comment]
I am no sure what that means. I see no clear function. I see a clearFile function but there is no prototype to call it.

While not ideal, I instead have directly removed the file from the files array outside the plugin using array manipulation.

**Comment by Sell24** [comment]
When you said clear, I thought you were referring to $upload.clear but in looking at the code I see you mean file.clear(). 

While this works, it also launches the start() function which will not work in my case since I am removing files (of wrong file type) from all/queue before initiating the upload.

**Comment by websanova** [comment]
The start on clear when upload hasn't started yet should be fixed now in v1.2.2-beta.
