### ISSUE TITLE
Enhancement: Option to don't add files of wrong extension/size to the queue

### ISSUE THREAD

**Issue by Sell24** [websanova/vue-upload#38]
Just a request to add an option to bypass adding a selected file to the queue/all if it is of the wrong extension or file size. 

I am using this in a form wizard, so I dont want the user to be able to advance if the file is incorrect. I get around it by trapping the error and removing it from both lists. But it would be nice to be able to avoid this since basically the user has chosen an incorrect file.

**Comment by websanova** [comment]
Did you try accept option?

https://github.com/websanova/vue-upload/blob/master/README.md#accept-

**Comment by Sell24** [comment]
I have but there is still the option to choose "All Files" if the user so wishes to do so. I have had users do all kinds of funky stuff so I want to cover my bases. I get around it now by flagging the error and deleting the last file in the onSelect but it would be nice to prevent this at the source

**Comment by websanova** [comment]
Not sure that's the best approach.

I think a simple v-if with some computed check would work better.

Normally I will put my list items into a separate component anyway.

That way you don't mess with the original selection which is never really a good idea (in case you wanted some dual mode or something).
