### ISSUE TITLE
Status code 413 does't trigger onError

### ISSUE THREAD

**Issue by vstruhar** [websanova/vue-upload#39]
First let me thank you for this great vue component.

I noticed that when a server returns 413 status code (Payload Too Large) the **onError** method is not triggered and the **state** ($upload.meta('image').state === 'uploading') is stuck in the _uploading_ state.

version: 1.2.3-beta

**Comment by websanova** [comment]
Sounds strange, it's only this error, have you tried other errors?

Are you using vue-resource, axios, other? Is the success callback
triggering ?

Million questions I can think of ;)

**Comment by vstruhar** [comment]
I'm getting 413 status code in the Network tab (dev tools), but the state is stuck at 'uploading' state.

I'm using axios for ajax calls.

Here is a code snippet:
![image](https://user-images.githubusercontent.com/6599021/46742574-95d26b00-cca7-11e8-8d18-480a702facca.png)

**Comment by websanova** [comment]
Not so familiar with axios, but I think maybe you are not capturing the
error. If it's just returning Promise, should probably be .then(success,
error).

**Comment by vstruhar** [comment]
Oh, so the vue-upload is not supposed to handle the error? In that case I can just catch the error with axios.

![image](https://user-images.githubusercontent.com/6599021/46792034-a97edf80-cd42-11e8-89fe-264dbaafac44.png)

But the last thing is to change the uploading state to 'error', is this possible?

**Comment by websanova** [comment]
ah, no, it means your `http` option is not set correctly.

Also it's set as an option with `on` method in your example. But actually this is a global option and should be set on the plugin.

**Comment by vstruhar** [comment]
Oh, I'm looking at the [readme](https://github.com/websanova/vue-upload#http-_http) at the "Example using Axios", but I don't seem to understand where to include that. Is there a code example where I can see it used properly?

**Comment by websanova** [comment]
~~~
import vueUpload from '@websanova/vue-upload';

Vue.use(vueUpload, {
    http: function () {   /* my http driver */    }
});
~~~

**Comment by vstruhar** [comment]
And it works! 
I also had to add the [parseErrors](https://github.com/websanova/vue-upload#parseerrors-_parseerrors) method. 

Hope this will help somebody in the future.

Thanks a lot! And again great vue component, will keep using it in my future projects :)
