### ISSUE TITLE
onEnd called before all files are complete

### ISSUE THREAD

**Issue by nlien** [websanova/vue-upload#44]
When multiple is true and selecting several files, it sometimes seems that onEnd is called before onSuccess.

I am console logging onSuccess and onEnd, and the result sometimes yields (eg. when selecting 2 files):
```
onSuccess..: 
onEnd...:
onSuccess..:
```

This is how I setup the plugin:
```
  created () {
    this.$upload.on('upload', {
      accept: 'image/jpeg, image/png, application/pdf',
      extensions: ['jpeg', 'jpg', 'png', 'pdf'],
      maxFilesSelect: 10,
      maxSizePerFile: 1024 * 1024 * 30, // 30 MB
      maxFilesInProgress: 2,
      multiple: true,
      onSuccess (file, response) {
        console.log('onSuccess..:')
      },
      onEnd () {
        console.log('onEnd...:')
      }
    })
  }
```
I am using the latest version p.t.

**Comment by websanova** [comment]
Ok, will take a look, for now I guess just check the queue lengths in onEnd

**Comment by websanova** [comment]
Should be fixed in latest.
