### ISSUE TITLE
File state doesn't change

### ISSUE THREAD

**Issue by ikmolbo** [websanova/vue-upload#45]
I'm building a simple upload list showing the progress of each upload. Although a successful upload will reach 100 percentComplete, the state remains "upload". Shouldn't it change to "success"? My server returns a 200 response. Is there anything else that needs to be done in order to update the file.state?

Thanks!

**Comment by websanova** [comment]
Sorry, been super busy lately, will try to take a look at this soon,
otherwise you can just take a peak in the source and submit a PR, the code
is not that complicated for this plugin.

**Comment by websanova** [comment]
Just testing this, seems fine to me.
