### ISSUE TITLE
onError is not called for frontend validations

### ISSUE THREAD

**Issue by baltom** [websanova/vue-upload#47]
When triggering the "file-max-select" error this doesnt come through onError callback. 

Currently im using a workaround to watch this.$upload.errors('name') in a watcher. And then getting the error through that. This showed another error where this.$upload.reset('name') does not clear the error list. So had to do this manually

**Comment by websanova** [comment]
Made some updates on this.

so actually the max-file-select is just too much of a special case. So I've removed it from the errors stack all together. You can now just use `onSelect`.

~~~
onSelect(files, error) {

    if (error) {
        // trigger something.
    }

}
~~~
