### ISSUE TITLE
Drag and drop isn't working

### ISSUE THREAD

**Issue by the94air** [websanova/vue-upload#48]
I am unable to get the multiple dropzone example on the README working. `$upload.dropzone('product-gallery').active` doesn't shows the 'drop here' div and do so the button text inside of `$upload.meta('product-gallery').state`. I also tried to make the dropzone work by adding the DOM element ID to the upload options but no luck. Other than this everything is working perfectly. I like how this package deals with uploading and especially the progress feature. Here is an example https://codesandbox.io/s/pm0k008ww7 I want to know if I am doing something wrong. It will be super helpful to even just get the example working. Thank you.

**Comment by websanova** [comment]
Did you set a dropzone id?

**Comment by the94air** [comment]
Yes, I did. I uploaded a clone of my component online for you to see https://codesandbox.io/s/pm0k008ww7. You will find the installation code inside of `index.js` and the upload component in `src/App.vue`. Your help is much appreciated.

**Comment by Samirovich** [comment]
@the94air Did you get it working?

**Comment by the94air** [comment]
I ended up creating a custom component using axios `onUploadProgress` for the progress bar and [cwait](https://github.com/charto/cwait) for parallel uploading. Right now you don't have to do all that hard work because you can use [vueclip](https://vueclip.adonisjs.com/) to do all that I did.
