### ISSUE TITLE
How can we get % on uploading?

### ISSUE THREAD

**Issue by winstonfale** [websanova/vue-upload#50]
Is there any way to detect the upload status % example like 1% 2% upto 100%?
so user can know if how many % now his uploading file

**Comment by maxflex** [comment]
@tonz341 there's a [percent](https://websanova.com/docs/vue-upload/methods#percent) method, but it doesn't work by default

If you are using axios update options as following:
```js
Vue.use(vueUpload, {
  http: function(data) {
    return axios.post(data.url, data.body, {
      onUploadProgress: data.progress
    })
    .then(data.success)
    .catch(data.error)
  }
})
```

**Comment by websanova** [comment]
https://websanova.com/docs/vue-upload/options#onprogress

You can console.log(arguments) to see what's there ;)
