### ISSUE TITLE
Make a preview?

### ISSUE THREAD

**Issue by movepixels** [websanova/vue-upload#52]
How or where would be the best spot to implement a thumbnail preview of file being uploaded.

I can code the image generation no problem. I am just trying to figure out where to do it?
In the onSelect but that just has an array of number of items, not the actual file name, since you would think that would be best spot?

Thoughts, suggestions?

**Comment by jamieconnor** [comment]
```
onSelect(files, error) {
          const file = files[0];
          // display a preview
          let fileReader = new FileReader();
          fileReader.addEventListener("load", () => {
            this.previewImage = event.target.result; // put this as your source
          });
          fileReader.readAsDataURL(file);
}
```

**Comment by websanova** [comment]
Actually this is already built in. You can generate a preview on the fly with the preview() call.

Unfortunately the documentation need some improvements. Been focusing on my vue-auth plugin lately so this is still in queue for an update.

So basically each "file" in the queues has a `preview` method.

So for instance:

```
var file = this.$upload.file();
var file2 = this.$upload.files()[0]; // same thing as above.

file.preview(); // triggers image preview generation (this take a lot of memory so not done automatically.
```

Then just use that in your preview

```
<img
    v-if="$upload.file().$raw"
    :src="$upload.file().$raw"
/>
```

So normally I would call that `file.preview()` in the `onSelect` method.

And yes, working on improvements here with a version 3 planned.

**Comment by jamieconnor** [comment]
Oh great, thank you very much. Great plugin.
