### ISSUE TITLE
Localized Error Messages

### ISSUE THREAD

**Issue by JZubero** [websanova/vue-upload#6]
It would be great to have localized error messages. I'd be happy to contribute the German translation if you incorporate the necessary logic.

**Comment by websanova** [comment]
Hmm, I think you should already be able to do this with any localization plugin. Each error has a `rule` parameter associated with it. So you could use that as a key in some `errors` object.

**Comment by websanova** [comment]
On a side note, maybe have to provide an additional parameter here then called `value` so that can be passed by as well.

**Comment by websanova** [comment]
This should be better support in lastest version `1.0.1-beta` as it supports arguments for options now which can be updated.
