### ISSUE TITLE
Problem when using currentFiles and a file is deleted

### ISSUE THREAD

**Issue by ghost** [websanova/vue-upload#8]
Hi,

When I'm using currentFiles :and I remove a file with $upload.remove(), and add again a file I got the maxFiles error. It's like currentFiles It does not take into consideration that we have deleted a file.

Without currentFiles everything work correctly.

Any Idee ?

**Comment by websanova** [comment]
Not sure, bit busy with things at the moment, but I can take a look at the end of this week.

**Comment by ghost** [comment]
You found the problem ?

**Comment by websanova** [comment]
I made a bunch of fixes not too long ago, would have to try again.
