### ISSUE TITLE
How to use this component?

### ISSUE THREAD

**Issue by felipeneuhauss** [websanova/vue-upload#9]
Hi Rob, how are you?

Seen your plugin, I couldn't figure out how to use this plugin inside a Vue js component. 

Do I have to import and use inside the components variable? And how to reference the variable $upload?

Thanks Rob!
Cheers!

**Comment by OzairP** [comment]
This is a super confusing component to use. The README needs an update and imo the plugin is not very friendly to use.

The plugin seems to create DOM elements but does not require you to write any components into your HTML, this is sort of unexpected and unpredictable. Secondly, the `#reset` function is a bit confusing, why does it exist?

**Comment by websanova** [comment]
It doesn't create any DOM elements, it just handles the uploads. and keeps
everything stored in an internal data object.

Reset does what a reset normally does, resets the component and clears the
data object ;)

**Comment by elaijuh** [comment]
I was also having problem understanding how to use drag and drop zone

**Comment by websanova** [comment]
Just create an element with an "Id" attribute and set that "id" as the
"dropzone" parameter.
